CREATE TABLE produto(
id BIGINT NOT NULL AUTO_INCREMENT,
codigo VARCHAR(10) NOT NULL,
nome_produto VARCHAR(100) NOT NULL,
medida VARCHAR(10) NOT NULL,
tbl CHAR(1) NOT NULL,
classe_produto VARCHAR(10) NOT NULL,
preco DECIMAL(10,2) NOT NULL,
obs TEXT,
datasys DATETIME NOT NULL,
PRIMARY KEY (id)
);
